### ISSUE TITLE
Looking for some support in generating graph diagram.

### ISSUE THREAD

**Issue by shamb0** [meppent/pellucid#6]
Hello @ewile

Thanks for this RUST tool.

May I know what are the options & solc version used to generate the upstream byte code.

https://github.com/meppent/pellucid/blob/ad52cb883bf82fc24efbd71f1b3ce3aa2249f307/contracts/simple/contract_0/bytecode.txt#L1

I was trying to compile from the source

https://github.com/meppent/pellucid/blob/main/contracts/simple/contract_0/Contract.sol

tried following solc options

```
solc --bin ./Contract.sol

solc --bin --optimize ./Contract.sol
```

> solc version

https://github.com/ethereum/solidity/releases/download/v0.8.7/solc-static-linux

```
solc --version                   

solc, the solidity compiler commandline interface
Version: 0.8.7+commit.e28d00a7.Linux.g++
```

And tried to get the graph diagram. I can see flow lines only for first two blocks.

![](https://i.imgur.com/JYjongy.png)

But with upstream Bytecode, all the blocks are connected by the flowlines

https://github.com/meppent/pellucid/blob/ad52cb883bf82fc24efbd71f1b3ce3aa2249f307/contracts/simple/contract_0/bytecode.txt#L1

![](https://i.imgur.com/c2zAiaJ.png)

Looks like there are some mismatches in generated bytecodes, and causing the flow lines failure.

![](https://i.imgur.com/RtSKDHj.png)

**Comment by ewile** [comment]
Hi @shamb0, 
Thanks for taking a look at Pellucid,
If I'm not wrong, the issue there is that you are giving the deployment bytecode. 
Pellucid is thus displaying the constructor of the contract, which is close to empty on our example Contract.sol.
To access the runtime bytecode, you can use `solc --bin-runtime`. 
Let me know if that helped!
\- MEP

**Comment by shamb0** [comment]
Thanks, @ewile. You are right. With runtime bincode it's working fine. 👍🏾
